#! /usr/bin/python

#print("base64 by uk")

import base64
import sys

if(len(sys.argv) !=3):
    print("useage:b64 {e|d} f\"<string>\"")
    exit(-1)

path = sys.argv[0]
option = sys.argv[1]
data = sys.argv[2]

if option == "-d":
    print(base64.b64decode(data.encode()).decode())
elif option == "-e":
    print(base64.b64encode(data.encode()).decode())


